# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-guardduty
  description: Terraform module to provision AWS Guard Duty
  homepage: https://cloudposse.com/accelerate
  topics: compliance, security, terraform, hcl2, terraform-modules

